name: Deployment

concurrency: production

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Tailscale
          uses: tailscale/github-action@v2
          with:
            oauth-client-id: ${{ secrets.TS_OAUTH_USER }}
            oauth-secret: ${{ secrets.TS_OAUTH_PASS }}
            version: 1.52.0
            hostname: 'jwind'
            tags: tag:ci
       
        - name: "Deploy"
          uses: milanmk/actions-file-deployer@master
          with:
            remote-protocol: "sftp"
            remote-host: "jwind"
            remote-user: "jwind"
            remote-password: ${{ secrets.SFTP_PASS }}
            remote-path: "/home/jwind/jwind.xyz"

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 'jwind'
            username: 'root'
            password: ${{ secrets.SFTP_PASS }}
            script: systemctl restart jwind.xyz && systemctl status jwind.xyz


