name: Deployment

concurrency: production

on:
  push:
    branches:
      - Test-(Pro)

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: SFTP SSH Action
        id: upload
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: '139.144.116.254'
          port: 22
          username: 'root'
          password: ${{ secrets.password }}
          localPath: './'
          remotePath: '/home/flask_m101/'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: '139.144.116.254'
          username: 'root'
          password: ${{ secrets.password }}
          port: 22
          script: systemctl restart video.service
