name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '170.187.225.114'
        port: 22
        username: 'root'
        password: ${{ secrets.password }}
        localPath: './'
        remotePath: '/home/flask_m101'
