name: Deployment

concurrency: production

on:
  push:
    branches:
      - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: 📂 SFTP uploader                       # Upload to SFTP 
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: '139.144.116.254'             # Recommended to put the credentials in github secrets.
          username: 'root'
          password: ${{ secrets.password }}
          compress: true                             # Compression                          # Optional, Force uploading all files, Default to false(upload only newer files).
          localDir: './'                              # Required, Absolute or relative to cwd.
          remoteDir: '/home/flask_m101/code'                             # Required, Absolute path only.
          exclude: '.git*,.DS_Store'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: '139.144.116.254'
          username: 'root'
          password: ${{ secrets.password }}
          port: 22
          script: systemctl restart video.service
