name: Deployment

concurrency: production

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
        - name: Tailscale
          uses: tailscale/github-action@v2
          with:
            oauth-client-id: ${{ secrets.TS_OAUTH_USER }}
            oauth-secret: ${{ secrets.TS_OAUTH_PASS }}
            tags: tag:ci
            version: 1.52.0
            hostname: 'github-action'
        - name: SFTP SSH Action
          id: upload
          uses: Creepios/sftp-action@v1.0.4
          with:
            host: 'jwind'
            port: 22
            username: 'jwind'
            password: ${{ secrets.SFTP_PASS }}
            localPath: './'
            remotePath: '/home/jwind/test'


