name: Deployment

concurrency: production

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
        - name: Tailscale
          uses: tailscale/github-action@v2
          with:
            authkey: ${{ secrets.TS_AUTH_KEY }}
            tags: tag:ci
            version: 1.52.0
            hostname: github-action
        - name: SFTP transfer
          uses: danhendrickson/sftp-transfer-action@v2023.51.2
          with:
            server: jwind
            user: jwind
            pass: ${{ secrets.SFTP_PASS }}
            port: 22
            local-path: ./
            remote-path: /home/jwind/


