name: Deployment

concurrency: production

on:
  push:
    branches:
      - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code                    
        uses: actions/checkout@v2
      - name: 📂 SFTP uploader                      
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: '139.144.116.254'               
          username: 'root'
          password: ${{ secrets.password }}
          compress: true
          localDir: './'                        
          remoteDir: '/home/flask_m101/code'  
          exclude: '.DS_STORE,vendor/'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: '139.144.116.254'
          username: 'root'
          password: ${{ secrets.password }}
          port: 22
          script: systemctl restart video.service
