name: Deployment

concurrency: production

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Tailscale
          uses: tailscale/github-action@v2
          with:
            oauth-client-id: ${{ secrets.TS_OAUTH_USER }}
            oauth-secret: ${{ secrets.TS_OAUTH_PASS }}
            version: 1.52.0
            hostname: 'github-action'
            tags: tag:ci
            
        - name: "Deploy"
          uses: milanmk/actions-file-deployer@master
          with:
            remote-protocol: "sftp"
            remote-host: "jwind"
            remote-user: "jwind"
            remote-password: ${{ secrets.SFTP_PASS }}
            remote-path: "/home/jwind/jwind.xyz"

        - name: Add SSH key
          id: ssh
          env:
            SSH_KEY: ${{ secrets.SSH_KEY }}
            MACHINE: jwind
          run: |
            mkdir -p ~/.ssh
            MACHINE_IP="$(tailscale ip -6 $MACHINE)"
            ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
            printf "%s" "$SSH_KEY" > ~/.ssh/key 
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/key
            ssh -i ~/.ssh/key "root@$MACHINE_IP" "systemctl restart jwind.xyz && systemctl status jwind.xyz"                    



