name: Deployment

concurrency: production

on:
  push:
    branches:
      - deploy

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: 'root'
          server: '139.144.116.254'
          port: 22 # default is 22
          password: ${{ secrets.password }}
          local_path: ./* # default is ./*
          remote_path: /home/flask_m101/code
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: '139.144.116.254'
          username: 'root'
          password: ${{ secrets.password }}
          port: 22
          script: systemctl restart video.service
