name: Deployment

concurrency: production

on:
  push:
    branches:
      - login-test

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '139.144.116.254'
        port: 22
        username: 'root'
        password: ${{ secrets.password }}
        localPath: './'
        remotePath: '/home/test-server'
